config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :vocabularies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "english", to: "vocabularies#english_to_japanies_mode"
  post "mistake_english", to: "vocabularies#mistake_english"
  post "mistake_japanies", to: "vocabularies#mistake_japanies"
  get "japanies", to: "vocabularies#japanies_to_english_mode"
  get "search_english", to: "searches#search_english"
  get "search_japanies", to: "searches#search_japanies"
  get "english_word_test", to: "vocabularies#english_word_test"
  get "japanies_meaning_test", to: "vocabularies#japanies_meaning_test"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  def self.search_english(search)
    return Vocabulary.all unless search
    Vocabulary.where(['word LIKE ?', "%#{search}%"])
  end

  def self.search_japanies(search)
    return Vocabulary.all unless search
    Vocabulary.where(['meaning LIKE ?', "%#{search}%"])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search_english
    @vocabularies = Vocabulary.search_english(params[:search])
    render :search_english
  end

  def search_japanies
    @vocabularies = Vocabulary.search_japanies(params[:search])
    render :search_japanies
  end
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  before_action :set_vocabulary, only: [:show, :edit, :update, :destroy]

  # GET /vocabularies
  # GET /vocabularies.json
  def index
    @vocabularies = Vocabulary.page(params[:page]).per(10)
  end


  def new
    @vocabulary = Vocabulary.new
  end

  # GET /vocabularies/1/edit
  def edit
  end

  # POST /vocabularies
  # POST /vocabularies.json
  def create
    @vocabulary = Vocabulary.new(vocabulary_params)

    respond_to do |format|
      if @vocabulary.save
        flash[:success] = '新しい単語を登録しました。'
        format.html { redirect_to @vocabulary}
        format.json { render :show, status: :created, location: @vocabulary }
      else
        flash.now[:danger] = '単語の登録に失敗しました。'
        format.html { render :new }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabularies/1
  # PATCH/PUT /vocabularies/1.json
  def update
    respond_to do |format|
      if @vocabulary.update(vocabulary_params)
        flash[:success] = '単語の編集に成功しました。'
        format.html { redirect_to @vocabulary}
        format.json { render :show, status: :ok, location: @vocabulary }
      else
        flash.now[:danger] = '単語の編集に失敗しました。'
        format.html { render :edit }
        format.json { render json: @vocabulary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabularies/1
  # DELETE /vocabularies/1.json
  def destroy
    @vocabulary.destroy
    flash[:success] = '単語を削除しました。'
    respond_to do |format|
      format.html { redirect_to vocabularies_url }
      format.json { head :no_content }
    end
  end

  def english_to_japanies_mode
    @vocabulary = Vocabulary.where( 'id >= ?', rand(Vocabulary.count) + 1 ).first
    @word = @vocabulary.word
    render :english_to_japanies_mode
  end

  def japanies_to_english_mode
    @meaning = Vocabulary.where( 'id >= ?', rand(Vocabulary.count) + 1 ).first.meaning
    render :japanies_to_english_mode
  end

  def mistake_english
    @vocabulary = Vocabulary.find_by(word: params[:vocabulary][:word])

    if @vocabulary.count == nil
      @vocabulary.count = 0
      @vocabulary.count += 1
    else
      @vocabulary.count += 1
    end

    flash.now[:danger] = "#{@vocabulary.word}の間違えた回数が#{@vocabulary.count}回になりました！"

    @vocabulary.save

    @word = Vocabulary.where( 'id >= ?', rand(Vocabulary.count) + 1 ).first.word
    render :english_to_japanies_mode
  end

  def mistake_japanies
    @vocabulary = Vocabulary.find_by(meaning: params[:vocabulary][:meaning])
    if @vocabulary.count == nil
      @vocabulary.count = 0
      @vocabulary.count += 1
    else
      @vocabulary.count += 1
    end

    flash.now[:danger] = "#{@vocabulary.word}の間違えた回数が#{@vocabulary.count}回になりました！"

    @vocabulary.save

    @meaning = Vocabulary.where( 'id >= ?', rand(Vocabulary.count) + 1 ).first.meaning
    render :japanies_to_english_mode
  end

  def english_word_test
    @words = []
    10.times do
      @words << Vocabulary.where( 'id >= ?', rand(Vocabulary.count) + 1 ).first.word
    end
    render :english_word_test
  end

  def japanies_meaning_test
    @meanings = []
    10.times do
      @meanings << Vocabulary.where( 'id >= ?', rand(Vocabulary.count) + 1 ).first.meaning
    end
    render :japanies_meaning_test
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocabulary
      @vocabulary = Vocabulary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocabulary_params
      params.require(:vocabulary).permit(:word, :meaning, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/homes/top.html.haml
.center.jumbotron
  .text-center
    %h1 単語帳アプリを使う！
    = link_to '単語一覧ページを閲覧する！', vocabularies_path, class: 'btn btn-lg btn-primary'

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to 'トップページ', root_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to '一覧ページ', vocabularies_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '英単語の登録', new_vocabulary_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              テストモード
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to '英単語→日本語', english_path, class: "dropdown-item" %>
              <%= link_to '日本語→英単語', japanies_path, class: "dropdown-item" %>
              <%= link_to '10問英単語テスト', english_word_test_path, class: "dropdown-item" %>
              <%= link_to '10問意味テスト', japanies_meaning_test_path, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              検索モード
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to '英単語検索モード', search_english_path, class: "dropdown-item" %>
              <%= link_to '意味検索モード', search_japanies_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>英単語アプリ</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </head>
  <body>
  <%= render 'layouts/navbar' %>

  <div class="container">
    <%= render 'layouts/flash_messages' %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/searches/_search.html.erb
<% if vocabularies %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>#</th>
    <th>英単語</th>
    <th>意味</th>
    <th>詳細ページ</th>
    <th>編集ページ</th>
    <th>削除ページ</th>
  </tr>
  </thead>

  <tbody>
  <% vocabularies.each do |vocabulary| %>
    <tr>
      <td><%= vocabulary.id %></td>
      <td><%= vocabulary.word %></td>
      <td><%= vocabulary.meaning %></td>
      <td><%= link_to 'Show', vocabulary %></td>
      <td><%= link_to 'Edit', edit_vocabulary_path(vocabulary) %></td>
      <td><%= link_to 'Destroy', vocabulary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/searches/search_english.html.erb
<div class="search" style="margin-bottom: 30px;">
  <div class="row">
    <div class="text-center", style="padding-top: 15px">
      <%= form_tag(search_english_path, method: :get,  class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search] %>
        </div>
        <div style="padding-left: 10px">
          <%= submit_tag '英単語を検索する', :word => nil, class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'search', vocabularies: @vocabularies %>

app/views/searches/search_japanies.html.erb
<div class="search" style="margin-bottom: 30px;">
  <div class="row">
    <div class="text-center", style="padding-top: 15px">
      <%= form_tag(search_japanies_path, method: :get,  class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search] %>
        </div>
        <div style="padding-left: 10px">
          <%= submit_tag '意味で検索する', :meaning => nil, class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'search', vocabularies: @vocabularies %>

app/views/vocabularies/_form.html.erb
<%= form_with(model: vocabulary, local: true) do |form| %>
  <% if vocabulary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vocabulary.errors.count, "error") %> prohibited this vocabulary from being saved:</h2>

      <ul>
      <% vocabulary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-6">
    <%= form.label "英単語" %>
    <%= form.text_field :word, class: "form-control" %>
  </div>

  <div class="form-group col-sm-6">
    <%= form.label "意味" %>
    <%= form.text_field :meaning, class: "form-control" %>
  </div>

  <div class="actions col-sm-6">
    <%= form.submit "新しい単語を登録する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/vocabularies/_vocabularies.html.haml
.row
  %table.table.table-bordered.table-dark
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} 英単語
        %th{:scope => "col"} 意味
        %th{:scope => "col"} 詳細ページへのリンク
        %th{:scope => "col"} 編集ページへのリンク
        %th{:scope => "col"} 削除ページへのリンク
    %tbody
      - vocabularies.each do |vocabulary|
        %tr
          %th{:scope => "row"}= vocabulary.id
          %td= vocabulary.word
          %td= vocabulary.meaning
          %td= link_to 'Show', vocabulary
          %td= link_to 'Edit', edit_vocabulary_path(vocabulary)
          %td= link_to 'Destroy', vocabulary, method: :delete, data: { confirm: 'Are you sure?' }
  = paginate @vocabularies

app/views/vocabularies/edit.html.haml
%h1 Editing Vocabulary
= render 'form', vocabulary: @vocabulary
= link_to 'Show', @vocabulary
|
= link_to 'Back', vocabularies_path

app/views/vocabularies/english_to_japanies_mode.html.erb
<div style="margin-top: 15px;">
  <h1>英語→日本語モード</h1>
</div>

<%= link_to "ランダムに英単語を表示させる", english_path, class: "btn btn-success" %>

<div style="margin-top: 15px;">
  <% if @word %>
    <div style="font-size: 30px;">
      英単語: <%= @word %>
    </div>
    <div style="padding-top: 10px;">
      <%= link_to "わからないボタン", mistake_english_path(@vocabulary, params: { vocabulary: { word: @word} }), class: "btn btn-danger", method: :post %>
    </div>
  <% end %>
</div>

app/views/vocabularies/english_word_test.html.erb
<table class="table table-bordered" style="margin-top: 15px;">
  <thead>
  <tr>
    <th>#</th>
    <th>英単語</th>
    <th>ボタン</th>
  </tr>
  </thead>

  <tbody>
  <% @words.each_with_index do |word, idx| %>
    <tr>
      <td><%= idx + 1 %></td>
      <td><%= word %></td>
      <td><%= link_to "わからないボタン", mistake_english_path(@vocabulary, params: { vocabulary: { word: word} }), class: "btn btn-danger", method: :post %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "もう一度10問単語テストをする", english_word_test_path, class: "btn btn-success" %>

app/views/vocabularies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>英単語一覧ページ</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>#</th>
    <th>英単語</th>
    <th>意味</th>
    <th>詳細ページ</th>
    <th>編集ページ</th>
    <th>削除ページ</th>
  </tr>
  </thead>

  <tbody>
  <% @vocabularies.each do |vocabulary| %>
    <tr>
      <td><%= vocabulary.id %></td>
      <td><%= vocabulary.word %></td>
      <td><%= vocabulary.meaning %></td>
      <td><%= link_to 'Show', vocabulary %></td>
      <td><%= link_to 'Edit', edit_vocabulary_path(vocabulary) %></td>
      <td><%= link_to 'Destroy', vocabulary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @vocabularies %>

app/views/vocabularies/japanies_meaning_test.html.erb
<table class="table table-bordered" style="margin-top: 15px;">
  <thead>
  <tr>
    <th>#</th>
    <th>意味</th>
    <th>ボタン</th>
  </tr>
  </thead>

  <tbody>
  <% @meanings.each_with_index do |meaning, idx| %>
    <tr>
      <td><%= idx + 1 %></td>
      <td><%= meaning %></td>
      <td><%= link_to "わからないボタン", mistake_japanies_path(@vocabulary, params: { vocabulary: { meaning: meaning} }), class: "btn btn-danger", method: :post %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "もう一度10問単語テストをする", japanies_meaning_test_path, class: "btn btn-success" %>

app/views/vocabularies/japanies_to_english_mode.html.erb
<div style="margin-top: 15px;">
  <h1>日本語→英単語モード</h1>
</div>

<%= link_to "ランダムに意味を表示させる", japanies_path, class: "btn btn-success" %>

<div style="margin-top: 15px;">
  <% if @meaning %>
    <div style="font-size: 30px;">
      英単語: <%= @meaning %>
    </div>
    <div style="padding-top: 10px;">
      <%= link_to "わからないボタン", mistake_japanies_path(@vocabulary, params: { vocabulary: { meaning: @meaning} }), class: "btn btn-danger", method: :post %>
    </div>
  <% end %>
</div>

app/views/vocabularies/new.html.erb
<h1 style="margin-top: 15px;">新しい単語を登録する</h1>

<%= render 'form', vocabulary: @vocabulary %>

app/views/vocabularies/show.html.haml
%p#notice= notice
%p
  %strong Word:
  = @vocabulary.word
%p
  %strong Meaning:
  = @vocabulary.meaning
%p
  %strong Count:
  = @vocabulary.count
= link_to 'Edit', edit_vocabulary_path(@vocabulary)
|
= link_to 'Back', vocabularies_path